name: Deploy Infrastructure (Docker)

on:
  push:
    paths:
      - "infra/docker/nginx/**"
      - "infra/docker/php/**"
      - "infra/docker/mysql/**"
      - "docker-compose.yml"
      - ".github/workflows/infra.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Determine Changed Services
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD)

          echo "Changed files: $(git diff --name-only HEAD)"

          files=(`git diff --name-only HEAD|tr '\n' ' ' `)
          for file in ${files[@]}; do
            echo ${file}
          done
          
          DEPLOY_NGINX=false
          DEPLOY_PHP=false
          DEPLOY_MYSQL=false
          DEPLOY_ALL=false

          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" =~ ^infra/docker/nginx/ ]]; then
              DEPLOY_NGINX=true
            elif [[ "$FILE" =~ ^infra/docker/php/ ]]; then
              DEPLOY_PHP=true
            elif [[ "$FILE" =~ ^infra/docker/mysql/ ]]; then
              DEPLOY_MYSQL=true
            elif [[ "$FILE" == "docker-compose.yml" ]]; then
              DEPLOY_ALL=true
            fi
          done

          echo "Nginx deployment flag: $DEPLOY_NGINX"
          echo "PHP deployment flag: $DEPLOY_PHP"
          echo "MySQL deployment flag: $DEPLOY_MYSQL"
          echo "Deploy all flag: $DEPLOY_ALL"

          echo "DEPLOY_NGINX=$DEPLOY_NGINX" >> $GITHUB_ENV
          echo "DEPLOY_PHP=$DEPLOY_PHP" >> $GITHUB_ENV
          echo "DEPLOY_MYSQL=$DEPLOY_MYSQL" >> $GITHUB_ENV
          echo "DEPLOY_ALL=$DEPLOY_ALL" >> $GITHUB_ENV

      - name: Display container deployment flags
        run: |
          echo "Nginx deployment flag: ${{ env.DEPLOY_NGINX }}"
          echo "PHP deployment flag: ${{ env.DEPLOY_PHP }}"
          echo "MySQL deployment flag: ${{ env.DEPLOY_MYSQL }}"
          echo "Deploy all flag: ${{ env.DEPLOY_ALL }}"

      # - name: Deploy via SSH
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /path/to/your/project

      #       if [[ "$DEPLOY_ALL" == "true" ]]; then
      #         echo "Updating all containers..."
      #         rsync -avz --delete infra/docker/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/your/project/infra/docker/
      #         docker-compose down
      #         docker-compose up -d --build
      #         exit 0
      #       fi

      #       if [[ "$DEPLOY_NGINX" == "true" ]]; then
      #         echo "Updating Nginx..."
      #         rsync -avz --delete infra/docker/nginx/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/your/project/infra/docker/nginx/
      #         docker-compose up -d --build nginx
      #       fi

      #       if [[ "$DEPLOY_PHP" == "true" ]]; then
      #         echo "Updating PHP..."
      #         rsync -avz --delete infra/docker/php/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/your/project/infra/docker/php/
      #         docker-compose up -d --build php
      #       fi

      #       if [[ "$DEPLOY_MYSQL" == "true" ]]; then
      #         echo "Updating MySQL..."
      #         rsync -avz --delete infra/docker/mysql/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/path/to/your/project/infra/docker/mysql/
      #         docker-compose up -d --build mysql
      #       fi
