name: Deploy Infrastructure (Docker)

on:
  push:
    paths:
      - "infra/docker/nginx/**"
      - "infra/docker/php/**"
      - "infra/docker/mysql/**"
      - "docker-compose.yml"
      - ".github/workflows/infra.yml"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: |
            infra/
          sparse-checkout-cone-mode: false

      - name: Determine Changed Services
        id: changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1)

          DEPLOY_NGINX=false
          DEPLOY_PHP=false
          DEPLOY_MYSQL=false

          for FILE in $CHANGED_FILES; do
            if [[ "$FILE" =~ ^infra/docker/nginx/ ]]; then
              DEPLOY_NGINX=true
            elif [[ "$FILE" =~ ^infra/docker/php/ ]]; then
              DEPLOY_PHP=true
            elif [[ "$FILE" =~ ^infra/docker/mysql/ ]]; then
              DEPLOY_MYSQL=true
            fi
          done

          echo "DEPLOY_NGINX=$DEPLOY_NGINX" >> $GITHUB_ENV
          echo "DEPLOY_PHP=$DEPLOY_PHP" >> $GITHUB_ENV
          echo "DEPLOY_MYSQL=$DEPLOY_MYSQL" >> $GITHUB_ENV

      - name: Deploy Nginx
        if: env.DEPLOY_NGINX == 'true'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: infra/docker/nginx
          remote_path: src/actions/infra/docker/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy PHP
        if: env.DEPLOY_PHP == 'true'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: infra/docker/php
          remote_path: src/actions/infra/docker/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy MySQL
        if: env.DEPLOY_MYSQL == 'true'
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avzr --delete
          path: infra/docker/mysql
          remote_path: src/actions/infra/docker/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}